### ISSUE TITLE
Обновление пакета PyPI

### ISSUE THREAD

**Issue by CallOfCrutches** [pavelmaksimov/clickhousepy#2]
Доброго времени суток! Простите за беспокойство, хотелось бы уточнить по обновлению пакета в PyPI. Будет ли оно с учетом последнего мержа и когда можно этого ожидать.

**Comment by pavelmaksimov** [comment]
сегодня сделаю

**Comment by CallOfCrutches** [comment]
Спасибо!

**Comment by pavelmaksimov** [comment]
обновил
pip install clickhousepy==2020.4.28
